import type { WizardResult, WizardStep } from "../types/wizard";

export const generateSteps = ({
  data,
}: {
  data: WizardResult;
}): WizardStep[] => [
  {
    question: "Are you hyperallergenic?",
    sliderLabels: ["No", "Yes"],
    id: "hyperallergenic",
    value: data.hyperallergenic,
    min: 0,
    max: 1,
    step: 1,
  },
  {
    question: "How important is animal welfare in general to you?",
    sliderLabels: [
      "as lang as my animals are fine",
      "-",
      "-",
      "-",
      "I am deeply involved",
    ],
    id: "welfare",
    value: data.welfare,
    min: 0,
    max: 4,
    step: 1,
  },
  {
    question:
      "How much time do you spent at home daily? - sleeping times excluded",
    sliderLabels: ["2", "4", "6", "8", "10", "10+"],
    id: "socialNeeds",
    value: data.socialNeeds,
    min: 0,
    max: 5,
    step: 1,
  },
  {
    question: "How much time do you have to play with your new cat daily?",
    sliderLabels: ["10 min", "20 min", "30 min", "40 min", "50 min", "1h+"],
    id: "activityLevel",
    value: data.activityLevel,
    min: 0,
    max: 5,
    step: 1,
  },
  {
    question: "Do you have a garden?",
    sliderLabels: ["No", "Yes"],
    id: "garden",
    value: data.garden,
    min: 0,
    max: 1,
    step: 1,
  },
  {
    question: "How many children do you have?",
    sliderLabels: ["0", "1", "2", "3", "4", "5+"],
    id: "familyFriendly",
    value: data.familyFriendly,
    min: 0,
    max: 5,
    step: 1,
  },
  {
    question: "Do you already have a pet?",
    sliderLabels: ["No", "Yes"],
    id: "dogFriendly",
    value: data.dogFriendly,
    min: 0,
    max: 1,
    step: 1,
  },
  {
    question: "How much do you love cuddles?",
    sliderLabels: ["1", "2", "3", "4", "5"],
    id: "affectionate",
    value: data.affectionate,
    min: 1,
    max: 5,
    step: 1,
  },
  {
    question: "Do you often host guests or parties?",
    sliderLabels: ["Never", "Sometimes", "Often"],
    id: "strangerFriendly",
    value: data.strangerFriendly,
    min: 0,
    max: 5,
    step: 3,
  },
  {
    question: "How much fluff can you handle?",
    sliderLabels: ["None", "Some", "Much"],
    id: "sheddingLevel",
    value: data.sheddingLevel,
    min: 0,
    max: 5,
    step: 3,
  },
  {
    question: "How fastly are you annoyed?",
    sliderLabels: ["0", "1", "2", "3", "4", "5"],
    id: "annoyingPotential",
    value: data.annoyingPotential,
    min: 0,
    max: 5,
    step: 1,
  },
];
